import type { Promotion } from './types'

const now = new Date()
const date = now.toLocaleDateString('en-CA')
export const db: Promotion[] = [
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Inactive',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Inactive',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Inactive',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Inactive',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Inactive',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
  {
    id: 1,
    code: 'SUMMER2024',
    description: 'test create promotion',
    startDate: String(date),
    toDate: String(date),
    status: 'Active',
    promoLines: [
      {
        id: 1,
        code: 'SUMMER2024FIRSTLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 10,
        promoDetails: [{
          id: 1,
          code: 'SUMMER2024FIRSTLINEDETAIL1',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        },
        {
          id: 2,
          code: 'SUMMER2024FIRSTLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
      {
        id: 2,
        code: 'SUMMER2024SECONDLINE',
        productReward: 'no',
        promoName: 'Siêu ưu đãi mùa hè',
        promoType: 'price',
        maxdiscount: 5,
        promoDetails: [{
          id: 3,
          code: 'SUMMER2024SECONDLINEDETAIL1',
          conditionApply: 300000,
          discount: 5,
          maxdiscount: 50000,
        },
        {
          id: 4,
          code: 'SUMMER2024SECONDLINEDETAIL2',
          conditionApply: 300000,
          discount: 10,
          maxdiscount: 100000,
        }],
      },
    ],
  },
]
