import type { UserProperties } from './types'
import avatar1 from '@images/avatars/avatar-1.png'
import avatar2 from '@images/avatars/avatar-2.png'
import avatar3 from '@images/avatars/avatar-3.png'
import avatar4 from '@images/avatars/avatar-4.png'
import avatar5 from '@images/avatars/avatar-5.png'
import avatar6 from '@images/avatars/avatar-6.png'

interface DB {
  users: UserProperties[]
}

export const db: DB = {
  users: [
    {
      id: 1,
      fullName: 'Galasasen Slixby',
      role: 'admin',
      address: 'El Salvador',
      phoneNumber: '(479) 232-9151',
      email: 'gslixby0@abc.net.au',
      status: 'active',
      avatar: '',
    },
    {
      id: 2,
      fullName: 'Halsey Redmore',
      role: 'manager',
      address: 'Albania',
      phoneNumber: '(472) 607-9137',
      email: 'hredmore1@imgur.com',
      status: 'active',
      avatar: avatar2,
    },
    {
      id: 3,
      fullName: 'Marjory Sicely',
      role: 'manager',
      address: 'Russia',
      phoneNumber: '(321) 264-4599',
      email: 'msicely2@who.int',
      status: 'inactive',
      avatar: avatar3,
    },
    {
      id: 4,
      fullName: 'Cyrill Risby',
      role: 'manager',
      address: 'China',
      phoneNumber: '(923) 690-6806',
      email: 'crisby3@wordpress.com',
      status: 'inactive',
      avatar: '',
    },
    {
      id: 5,
      fullName: 'Maggy Hurran',
      role: 'staff',
      address: 'Pakistan',
      phoneNumber: '(669) 914-1078',
      email: 'mhurran4@yahoo.co.jp',
      status: 'active',
      avatar: avatar5,
    },
    {
      id: 6,
      fullName: 'Silvain Halstead',
      role: 'staff',
      address: 'China',
      phoneNumber: '(958) 973-3093',
      email: 'shalstead5@shinystat.com',
      status: 'active',
      avatar: '',
    },
    {
      id: 7,
      fullName: 'Breena Gallemore',
      role: 'customer',
      address: 'Canada',
      phoneNumber: '(825) 977-8152',
      email: 'bgallemore6@boston.com',
      status: 'active',
      avatar: avatar1,
    },
    {
      id: 8,
      fullName: 'Kathryne Liger',
      role: 'customer',
      address: 'France',
      phoneNumber: '(187) 440-0934',
      email: 'kliger7@vinaora.com',
      status: 'active',
      avatar: '',
    },
    {
      id: 9,
      fullName: 'Franz Scotfurth',
      role: 'customer',
      address: 'China',
      phoneNumber: '(978) 146-5443',
      email: 'fscotfurth8@dailymotion.com',
      status: 'inactive',
      avatar: avatar1,
    },
    {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: avatar3,
    },
    {
      id: 11,
      fullName: 'Jonah Wharlton',
      role: 'customer',
      address: 'United States',
      phoneNumber: '(176) 532-6824',
      email: 'jwharltona@oakley.com',
      status: 'inactive',
      avatar: '',
    },
    {
      id: 12,
      fullName: 'Seth Hallam',
      role: 'customer',
      address: 'Peru',
      phoneNumber: '(234) 464-0600',
      email: 'shallamb@hugedomains.com',
      status: 'active',
      avatar: avatar3,
    },
    {
      id: 13,
      fullName: 'Yoko Pottie',
      role: 'customer',
      address: 'Philippines',
      phoneNumber: '(907) 284-5083',
      email: 'ypottiec@privacy.gov.au',
      status: 'inactive',
      avatar: avatar6,
    },
    {
      id: 14,
      fullName: 'Maximilianus Krause',
      role: 'staff',
      address: 'Congo',
      phoneNumber: '(167) 135-7392',
      email: 'mkraused@stanford.edu',
      status: 'active',
      avatar: '',
    },
    {
      id: 15,
      fullName: 'Zsazsa McCleverty',
      role: 'customer',
      address: 'France',
      phoneNumber: '(317) 409-6565',
      email: 'zmcclevertye@soundcloud.com',
      status: 'active',
      avatar: avatar3,
    },
    {
      id: 16,
      fullName: 'Bentlee Emblin',
      role: 'customer',
      address: 'Spain',
      phoneNumber: '(590) 606-1056',
      email: 'bemblinf@wired.com',
      status: 'active',
      avatar: avatar4,
    },
    {
      id: 17,
      fullName: 'Brockie Myles',
      role: 'customer',
      address: 'Poland',
      phoneNumber: '(553) 225-9905',
      email: 'bmylesg@amazon.com',
      status: 'active',
      avatar: avatar1,
    },
    {
      id: 18,
      fullName: 'Bertha Biner',
      role: 'customer',
      address: 'Yemen',
      phoneNumber: '(901) 916-9287',
      email: 'bbinerh@mozilla.com',
      status: 'active',
      avatar: avatar3,
    },
    {
      id: 19,
      fullName: 'Travus Bruntjen',
      role: 'admin',
      address: 'France',
      phoneNumber: '(524) 586-6057',
      email: 'tbruntjeni@sitemeter.com',
      status: 'active',
      avatar: '',
    },
    {
      id: 20,
      fullName: 'Wesley Burland',
      role: 'staff',
      address: 'Honduras',
      phoneNumber: '(569) 683-1292',
      email: 'wburlandj@uiuc.edu',
      status: 'inactive',
      avatar: avatar5,
    },
    {
      id: 21,
      fullName: 'Selina Kyle',
      role: 'admin',
      address: 'USA',
      phoneNumber: '(829) 537-0057',
      email: 'irena.dubrovna@wayne.com',
      status: 'active',
      avatar: '',
    },
    {
      id: 22,
      fullName: 'Jameson Lyster',
      role: 'customer',
      address: 'Ukraine',
      phoneNumber: '(593) 624-0222',
      email: 'jlysterl@guardian.co.uk',
      status: 'inactive',
      avatar: avatar6,
    },
    {
      id: 23,
      fullName: 'Kare Skitterel',
      role: 'customer',
      address: 'Poland',
      phoneNumber: '(254) 845-4107',
      email: 'kskitterelm@ainyx.com',
      status: 'active',
      avatar: avatar2,
    },
    {
      id: 24,
      fullName: 'Cleavland Hatherleigh',
      role: 'admin',
      address: 'Brazil',
      phoneNumber: '(700) 783-7498',
      email: 'chatherleighn@washington.edu',
      status: 'active',
      avatar: '',
    },
    {
      id: 25,
      fullName: 'Adeline Micco',
      role: 'admin',
      address: 'France',
      phoneNumber: '(227) 598-1841',
      email: 'amiccoo@whitehouse.gov',
      status: 'active',
      avatar: '',
    },
  ],
}
