import type { Invoice } from '@/plugins/fake-api/handlers/apps/reservation/types'

export const database: Invoice[] = [
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
  {
    id: 'RE-1',
    orderDate: '2024-02-24',
    startDate: '2024-03-25',
    client: {
      id: 10,
      fullName: 'Jillene Bellany',
      role: 'customer',
      address: 'Jamaica',
      phoneNumber: '(589) 284-6732',
      email: 'jbellany9@kickstarter.com',
      status: 'inactive',
      avatar: '',
    },
    busNumber: 'HH-223',
    total: 3428000,
    paymentStatus: 'Đã thanh toán',
    status: 'Active',
  },
]
